/*
 * Copyright 2024 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include <stddef.h>
#include <stdio.h>

#include "mmbuf.h"
#include "core/autogen/mmagic_core_data.h"
#include "m2m_api/autogen/mmagic_m2m_wlan.h"
#include "m2m_api/autogen/mmagic_m2m_ip.h"
#include "m2m_api/autogen/mmagic_m2m_ping.h"
#include "m2m_api/autogen/mmagic_m2m_iperf.h"
#include "m2m_api/autogen/mmagic_m2m_sys.h"
#include "m2m_api/autogen/mmagic_m2m_tcp.h"
