/*
 * Copyright 2024 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "core/autogen/mmagic_core_data.h"
#include "m2m_api/mmagic_m2m_agent.h"

/********* Enumerations **********/
enum mmagic_wlan_vars
{
    mmagic_wlan_var_ampdu_enabled,
    mmagic_wlan_var_bssid,
    mmagic_wlan_var_cac_enabled,
    mmagic_wlan_var_country_code,
    mmagic_wlan_var_fragment_threshold,
    mmagic_wlan_var_max_health_check_intvl_ms,
    mmagic_wlan_var_min_health_check_intvl_ms,
    mmagic_wlan_var_offload_arp_refresh_s,
    mmagic_wlan_var_offload_arp_response,
    mmagic_wlan_var_password,
    mmagic_wlan_var_pmf_mode,
    mmagic_wlan_var_power_save_mode,
    mmagic_wlan_var_raw_priority,
    mmagic_wlan_var_rts_threshold,
    mmagic_wlan_var_security,
    mmagic_wlan_var_sgi_enabled,
    mmagic_wlan_var_ssid,
    mmagic_wlan_var_station_type,
    mmagic_wlan_var_subbands_enabled,
};

/**
 * Process the received M2M buffer.
 *
 * @param  agent   Reference to the M2M Agent context.
 * @param  sid     The stream ID this buffer was received on.
 * @param  header  The M2M header containing the subsystem, command and subcommand.
 * @param  cmd_buf The @c mmbuf with the buffer to be processed.
 * @return         An @c mmbuf with the response.
 */
struct mmbuf *mmagic_m2m_wlan_process(struct mmagic_m2m_agent *agent, uint8_t sid,
                                      struct mmagic_m2m_command_header *header,
                                      struct mmbuf *cmd_buf);
